/// Flutter icons SpecialityIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SpecialityIcons
///      fonts:
///       - asset: fonts/SpecialityIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SpecialityIcons {
  SpecialityIcons._();

  static const _kFontFam = 'SpecialityIcons';
  static const String? _kFontPkg = null;

  static const IconData cardiology_and_thoracic_surgery = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audiology = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData family = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orthopedics = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData general_practice = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData physiotherapy = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plastic_surgery = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dietitian_and_nutrition = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phoniatrics = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pediatrics_and_new_born = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData geriatrics = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hematology = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hepatology = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData internal_medicine = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ivf = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData neurosurgery = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData psychiatry = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinal_surgery = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oncology = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ear_nose_throat = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData urology = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData opthalmology = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData labortaries = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cartboard_3 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nephrology = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dentistry = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pediatrics = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sport_injuries = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spinal_surgery_2 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vascular_surgery = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleep_apnea = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pain_management = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData laparoscopic_ = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData allergy = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData andrology = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData artboard_3 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardiology_and_vascular_disease = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData neurology = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gastroenterology = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gastroenterology_and_endoscopy = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardiology_and_vascular_disease2 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diagnostic_radiology = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dermatology = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rheumatology = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gynaecology_and_infertility = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData general = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chest = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
